### ISSUE TITLE
Advice on how to integrate live555 on a project

### ISSUE THREAD

**Issue by fraviofii** [melchi45/live555#5]
Hello,

I'm trying to add live555 on a cmake based project. I'm using this repository to build the library. When I use `add_subdirectory`, it works. I am building a static library in Linux, without epoll and without ssl.

When I integrate to the project, I am unable to compile the application, because the file `liveMedia.hh` is not found.

Could you please give me some basic advice on what should I place on my main `CMakelists.txt`  file to be able to use the library?

**Comment by melchi45** [comment]
This live555 need to include manually with each the header files on each sub directory like BasicUsageEnvironment/include, sageEnvironment/include, groupsock/include, liveMedia/include. If you want to need the reference for this library usage, you can show the this CMakeLists.txt on rtspclient_with_opengl: https://github.com/melchi45/rtspclient_with_opengl/blob/master/CMakeLists.txt
